
name: Ejecutar aplicación de línea de comandos Swift
description: Esta acción ejecuta una aplicación de línea de comandos Swift

inputs:
  arguments:
    description: 'Argumentos para pasar a la aplicación'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Instalar Swift
      run: |
        sudo apt-get update
        sudo apt-get install swift
        
        # Si estás en macOS, puedes usar el siguiente comando para instalar Swift
        # brew install swift
        
    #    - name: Clonar repositorio
    # run: |
#    git clone https://github.com/tu-usuario/tu-repositorio.git
         # Opcionalmente, puedes copiar tu código Swift directamente aquí en lugar de clonar un repositorio
        
    - name: Compilar y ejecutar
      run: | 
        swift build
        .build/debug/Test_Github_Action ${{ inputs.arguments }}
