name: Ejecutar aplicación de línea de comandos Swift
description: Esta acción ejecuta una aplicación de línea de comandos Swift
author: 'Asiel Cabrera'

inputs:
  myInput:
    description: 'Descripción de la entrada myInput'
    required: true
    default: 'Valor predeterminado para myInput'
  optionalInput:
    description: 'Descripción de la entrada optionalInput'
    required: false
    default: 'Valor predeterminado para optionalInput'
outputs:
  myOutput:
    description: 'Descripción de la salida myOutput'

runs:
  using: 'composite'
  steps:
  
    - name: Prueba
      run: echo Hello ${{ inputs.myInput }}
      shell: bash
  
    - name: Instalar Swift
      run: |
        sudo apt-get update
        sudo apt-get install swift
        
        # Si estás en macOS, puedes usar el siguiente comando para instalar Swift
        # brew install swift
        
      shell: bash
      
    - name: Clonar repositorio
      run: |
        git clone https://github.com/asielcabrera/Test_Github_Action.git
      # Opcionalmente, puedes copiar tu código Swift directamente aquí en lugar de clonar un repositorio
        
      shell: bash
        
    - name: Compilar y ejecutar
      run: |
        cd Test_Github_Action
        swift build
        .build/debug/Test_Github_Action ${{ inputs.arguments }}
        
      shell: bash
