name: Run Swift command-line application
description: This action executes a Swift command-line application
author: 'Asiel Cabrera'

inputs:
  myInput:
    description: 'Description of the myInput entry'
    required: true
    default: 'Default value for myInput'
  optionalInput:
    description: 'Description of the optionalInput entry'
    required: false
    default: 'Default value for optionalInput'
  name:
    required: true
outputs:
  myOutput:
    description: 'Description of the myOutput output'

runs:
  using: 'composite'
  steps:
    - name: Install Swift
      run: |
        sudo apt-get update
        sudo apt-get install swift
            
      shell: bash
      
    - name: Clone repository
      run: |
        git clone https://github.com/asielcabrera/Test_Github_Action.git
        
      shell: bash
        
    - name: Compile and execute
      id: comandexec
      env:
        INPUT_NAME: ${{ inputs.name }}
        INPUT_MYINPUT: ${{ inputs.myInput }}
      run: |
        cd Test_Github_Action
        swift build
        swift run
      shell: bash
    
    - name: test output
      run: echo ${{ steps.comandexec.outputs.myOutput }}
      shell: bash
